### ISSUE TITLE
Api ratelimits?

### ISSUE THREAD

**Issue by xXBuilderBXx** [GameAPIs/Issues#1]
API: Minecraft

API's URL: https://docs.gameapis.net/docs/mc/query

Description of issue: Hi this is not an issue but i was wonder what kind of ratelimits have been set on the api specifically getting a servers status as i wanted to use your API to ping multiple servers and yes ik that you can ping multiple servers with 1 request. Also great work on the website and APIs 👍

**Comment by Yive** [comment]
None of the APIs on the site have a rate limit. Though pinging multiple servers does have a limit of 5 servers. This is just to avoid long response times.

**Comment by xXBuilderBXx** [comment]
Ok thanks for the info on limit of 5 servers ill only do a max of 3
