### ISSUE TITLE
Was server shutdown??

### ISSUE THREAD

**Issue by gunyu1019** [GameAPIs/Issues#14]
API: All

API's URL: https://use.gameapis.net/mc/images/skin/Cobwebster/true

Description of issue:Did Gameapis' server explode? The server is not connected at this time. 09-Dec
What I can see is 404 Not Found.
It's nginx.

**Comment by ItsTauTvyDas** [comment]
I think so, because he post source code of GameAPIs website (If that project will be alive, I don't think he will post source code).. Take a look https://github.com/Yive/GameAPIs
