### ISSUE TITLE
Mc Query Extensive error on BungeeCord

### ISSUE THREAD

**Issue by MineSAT** [GameAPIs/Issues#2]
API: MC Extensive

API's URL: https://use.gameapis.net/mc/query/extensive/

Description of issue: 
No show anything on Bungee server's, but Info Query shows information of Bungee server.

**Comment by Yive** [comment]
Extensive is meant for direct contact to a real Minecraft server instance, it will never work on BungeeCord or Lilypad because as far as I know, neither of those actually support udp queries.

**Comment by MineSAT** [comment]
Ok thanks ;)
