### ISSUE TITLE
MC Query Extensive doesnt respond to vanilla servers?

### ISSUE THREAD

**Issue by TheMaikas** [GameAPIs/Issues#6]
API:
Minecraft Server API
API's URL:
https://use.gameapis.net/mc/query/extensive/einfachmc.de
Description of issue:
It doenst respond. It might be because of the plugins, it cant find?

**Comment by Yive** [comment]
I just checked & it appears to be an issue which I forgot to fix within the extensive querying. It was fixed within https://use.gameapis.net/mc/query/info/einfachmc.de though.

It should be fixed by tomorrow for requests to the extensive api.
